import './globals.css'
// import { Open_Sans } from 'next/font/google'

// const inter = Open_Sans({ subsets: ['latin'], weight:['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`bg-zinc-950`}>
        {children}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
      </body>
    </html>
  )
}
